### ISSUE TITLE
Upgrading

### ISSUE THREAD

**Issue by dmytrokohut** [finr1r/DMBRB#4]
The next stage is the upgrading of smart-contracts and tests.
For more efficiency, it is probably a good idea to change some code in Solidity for assembly code which consumes less gas than high-level Solidity.
After smart-contracts will be changed it is necessary to change the tests as well.

**Comment by Milkho** [comment]
If you are talking about a storage library support, then you **are completely wrong**. 
I used this library in my project in order to be able to not depend on the data structures provided by solidity within a single contract. 
StorageInteface provides a flexible way to store complex structures (and simple ones too) using the structure name as a key. At the same time, Storage contract only stores the data without having the information how this data is organized. 

When working with this library. **more gas is spent**, but we have a more flexible solution.

**Comment by dmytrokohut** [comment]
Hi @Milkho,
First of all, I meant to change some pieces of code into an assembly code as this is a less costly way of working.
What about StorageInterface you are right, and therefore on cost issues, I will not, at least now, change the interfaces to libraries.

**Comment by dmytrokohut** [comment]
There is a trouble with rewriting Solidity code into assembly code - it seems still not possible to make a transaction from the assembly, in my case, a lot of code leaves without changing. So if something will be changed it will be really small pieces of code.
